include_guard(GLOBAL)

foreach (LANG IN ITEMS CXX C)
  define_property(${LANG}_CLANG_CHECK_CHECKS SCOPE TARGET)
  define_property(${LANG}_CLANG_CHECK_WARNINGS_AS_ERRORS SCOPE TARGET)
  define_property(${LANG}_CLANG_CHECK_ANALYZE_TEMPORARY_DTORS SCOPE TARGET)
  define_property(${LANG}_CLANG_CHECK_FORMAT_STYLE SCOPE TARGET)
  define_property(${LANG}_CLANG_CHECK_USER SCOPE TARGET)
endforeach()
