include_guard(GLOBAL)

foreach (LANG IN ITEMS CXX C)
  define_property(TARGET PROPERTY CXX_CLANG_CHECK_CHECKS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY CXX_CLANG_CHECK_WARNINGS_AS_ERRORS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY CXX_CLANG_CHECK_ANALYZE_TEMPORARY_DTORS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY CXX_CLANG_CHECK_FORMAT_STYLE BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY CXX_CLANG_CHECK_USER BRIEF_DOCS "" FULL_DOCS "")
endforeach()
