include_guard(GLOBAL)

foreach (LANG IN ITEMS CXX C)
  define_property(TARGET PROPERTY ${LANG}_IWYU_HOW_TO_DEBUG BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_MAPPING_FILE BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_CHECK_ALSO BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_CWD BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_NO_DEFAUT_MAPPINGS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_PCH_IN_CODE BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_PREFIX_HEADER_INCLUDES BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_TRANSITIVE_INCLUDES_ONLY BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_MAX_LINE_LENGTH BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_NO_COMMENTS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_NO_FWD_DECLS BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_VERBOSE BRIEF_DOCS "" FULL_DOCS "")
  define_property(TARGET PROPERTY ${LANG}_IWYU_QUOTED_INCLUDES_FIRST BRIEF_DOCS "" FULL_DOCS "")
  set_property(GLOBAL APPEND
    PROPERTY IXM_TARGET_PROPERTIES
      ${LANG}_IWYU_HOW_TO_DEBUG
      ${LANG}_IWYU_MAPPING_FILE
      ${LANG}_IWYU_CHECK_ALSO
      ${LANG}_IWYU_CWD
      ${LANG}_IWYU_NO_DEFAULT_MAPPINGS
      ${LANG}_IWYU_PCH_IN_CODE
      ${LANG}_IWYU_PREFIX_HEADER_INCLUDES
      ${LANG}_IWYU_TRANSITIVE_INCLUDES_ONLY
      ${LANG}_IWYU_MAX_LINE_LENGTH
      ${LANG}_IWYU_NO_COMMENTS
      ${LANG}_IWYU_NO_FWD_DECLS
      ${LANG}_IWYU_VERBOSE
      ${LANG}_IWYU_QUOTED_INCLUDES_FIRST)
endforeach()
