include_guard(GLOBAL)

function (ixm_color_add name r g b)
  set_property(GLOBAL PROPERTY ixm::color::${name} ${r} ${g} ${b})
  set_property(GLOBAL APPEND PROPERTY ixm::colors ${name})
endfunction ()

function (ixm_color_initialize)
  set(conemu OFF)
  if (DEFINED ENV{ConEmuANSI})
    set(conemu $ENV{ConEmuANSI})
  endif()
  if (CMAKE_HOST_WIN32 AND NOT conemu AND NOT CMAKE_GENERATOR STREQUAL "Ninja")
    return()
  endif()
  string(ASCII 27 esc)
  get_property(colors GLOBAL PROPERTY ixm::colors)
  foreach (color IN LISTS colors)
    get_property(values GLOBAL PROPERTY ixm::color::${color})
    set(.${color} "${esc}[38;2;${values}m" CACHE INTERNAL "")
  endforeach()
  set(.default "${esc}[m" CACHE INTERNAL "")
endfunction()

ixm_color_initialize()
