include_guard(GLOBAL)

# TODO: This *should* be in the FindIWYU.cmake file...
# TODO: or at the very least, be a function call to set them all

define_property(TARGET PROPERTY IWYU_HOW_TO_DEBUG BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_MAPPING_FILE BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_CHECK_ALSO BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_CWD BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_NO_DEFAUT_MAPPINGS BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_PCH_IN_CODE BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_PREFIX_HEADER_INCLUDES BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_TRANSITIVE_INCLUDES_ONLY BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_MAX_LINE_LENGTH BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_NO_COMMENTS BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_NO_FWD_DECLS BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_VERBOSE BRIEF_DOCS "" FULL_DOCS "")
define_property(TARGET PROPERTY IWYU_QUOTED_INCLUDES_FIRST BRIEF_DOCS "" FULL_DOCS "")

set_property(GLOBAL APPEND
  PROPERTY IXM_TARGET_PROPERTIES
    IWYU_HOW_TO_DEBUG
    IWYU_MAPPING_FILE
    IWYU_CHECK_ALSO
    IWYU_CWD
    IWYU_NO_DEFAULT_MAPPINGS
    IWYU_PCH_IN_CODE
    IWYU_PREFIX_HEADER_INCLUDES
    IWYU_TRANSITIVE_INCLUDES_ONLY
    IWYU_MAX_LINE_LENGTH
    IWYU_NO_COMMENTS
    IWYU_NO_FWD_DECLS
    IWYU_VERBOSE
    IWYU_QUOTED_INCLUDES_FIRST)
