include_guard(GLOBAL)

include(CMakePushCheckState)
include(CheckIncludeFiles)
include(ParentScope)

function (check_headers headers variable)
  set(option QUIET)
  set(single LANGUAGE)
  set(multi FLAGS DEFINITIONS INCLUDES LIBRARIES)
  cmake_parse_arguments(ARG "${option}" "${single}" "${multi}" ${ARGN})

  cmake_push_check_state()
  set(CMAKE_REQUIRED_DEFINITIONS ${ARG_DEFINITIONS})
  set(CMAKE_REQUIRED_LIBRARIES ${ARG_LIBRARIES})
  set(CMAKE_REQUIRED_INCLUDES ${ARG_INCLUDES})
  set(CMAKE_REQUIRED_FLAGS ${ARG_FLAGS})
  set(CMAKE_REQUIRED_QUIET OFF)
  if (ARG_QUIET)
    set(CMAKE_REQUIRED_QUIET ON)
  endif ()
  check_include_files(${headers} ${variable} LANGUAGE ${ARG_LANGUAGE})
  cmake_pop_check_state()
  parent_scope(${variable})
endfunction ()
