include_guard(GLOBAL)

# TODO: This could be refined a *lot* better
#[[ Generates a unity build file based on the sources given ]]
function(ixm_generate_unity_build_file target)
  genex(expressions $<
    $<BOOL:$<TARGET_PROPERTY:${target},UNITY_SOURCES>>:
    "#include<"
    $<JOIN:
      $<TARGET_PROPERTY:${target},UNITY_SOURCES>,
      "$<ANGLE-R>\n#include<>$<ANGLE-R>"
    >
  >)
  string(JOIN "\n" content
    "/* GENERATED BY IXM. DO NOT EDIT */"
    ${expressions})
  file(GENERATE
    OUTPUT $<TARGET_PROPERTY:${target},UNITY_BUILD_FILE>
    CONTENT ${content}
    CONDITION $<BOOL:$<TARGET_PROPERTY:${target},UNITY_SOURCES>>)
endfunction()
