include_guard(GLOBAL)

function (coven_detect_directory var dir)
  set(detected OFF)
  if (IS_DIRECTORY "${PROJECT_SOURCE_DIR}/${dir}")
    set(detected ON)
  endif()
  dict(INSERT coven::detect::${PROJECT_NAME} ${var} ${detected})
endfunction ()

function (coven_detect_launchers)
  find_package(SCCache)
  find_package(CCache)
endfunction()

function (coven_detect_gohugo out-var)
  foreach (extension IN ITEMS toml yaml json)
    if (EXISTS "${PROJECT_SOURCE_DIR}/docs/config.${extension}")
      find_package(Hugo)
      break()
    endif()
  endforeach()
endfunction ()

function (coven_detect_jekyll out-var)
  if (EXISTS "${PROJECT_SOURCE_DIR}/docs/_config.yml")
    find_package(Jekyll)
  endif()
endfunction ()

function (coven_detect_mkdocs out-var)
  if (EXISTS "${PROJECT_SOURCE_DIR}/docs/mkdocs.yml")
    find_package(MkDocs)
  endif()
endfunction ()

function (coven_detect_sphinx out-var)
  if (EXISTS "${PROJECT_SOURCE_DIR}/docs/conf.py")
    find_package(Sphinx)
  endif()
endfunction()
