include_guard(GLOBAL)

function (coven_package_init)
  string(MAKE_C_IDENTIFIER "${PROJECT_NAME}" project)
  string(TOUPPER "${project}" project)
  if (NOT WIN32 AND NOT APPLE AND NOT ANDROID)
    option(${project}_PACKAGE_APPIMAGE)
    option(${project}_PACKAGE_RPM)
    option(${project}_PACKAGE_DEB)
  endif()
  option(${project}_PACKAGE_ARCHIVE)
  option(${project}_PACKAGE_BUNDLE)
  option(${project}_PACKAGE_NUGET)
  option(${project}_PACKAGE_MSI)
endfunction()
