include_guard(GLOBAL)

function (ixm_dict_insert_begin action)
  list(LENGTH ARGN length)
  if (NOT length)
    log(FATAL "dict(${action}) requires at least one value to be inserted")
  endif()
  ixm_dict_create(${dict})
endfunction()

function (ixm_dict_insert_end)
  void(keys index)
  ixm_dict_keys(${dict} keys)
  list(FIND keys ${key} index)
  if (index EQUAL -1)
    string(ASCII 192 C0)
    set_property(TARGET ${dict} APPEND PROPERTY "INTERFACE_${C0}" "${key}")
  endif()
endfunction()

function (ixm_dict_assign dict key)
  ixm_dict_insert_begin("ASSIGN" ${ARGN})
  set_property(TARGET ${dict} PROPERTY "INTERFACE_${key}" ${ARGN})
  ixm_dict_insert_end(${dict} ${key})
endfunction()

function (ixm_dict_append dict key)
  ixm_dict_insert_begin("APPEND" ${ARGN})
  set_property(TARGET ${dict} APPEND PROPERTY "INTERFACE_${key}" ${ARGN})
  ixm_dict_insert_end(${dict} ${key})
endfunction()

function (ixm_dict_concat dict key)
  ixm_dict_insert_begin("CONCAT" ${ARGN})
  set_property(TARGET ${dict} APPEND_STRING PROPERTY "INTERFACE_${key}" ${ARGN})
  ixm_dict_insert_end(${dict} ${key})
endfunction()