include_guard(GLOBAL)

function (ixm_find_confirm)
  set(name ${CMAKE_FIND_PACKAGE_NAME})
  set(${name}_FOUND OFF PARENT_SCOPE)
  if (NOT TARGET ${name}::${name})
    return()
  endif()

  foreach (component IN LISTS ${name}_FIND_COMPONENTS)
    if (${name}_FIND_REQUIRED_${component})
      list(APPEND required-components ${component})
    endif()
  endforeach()
  foreach (component IN LISTS required-components)
    if (NOT TARGET ${name}::${component})
      set(${name}_FOUND OFF PARENT_SCOPE)
      return()
    endif()
  endforeach ()
  set(${name}_FOUND ON PARENT_SCOPE)
endfunction()
