include_guard(GLOBAL)

function (ixm_coven_component_create component)
  string(TOUPPER "${component}" option)
  if (NOT BUILD_${option})
    return()
  endif()
  glob(items "${PROJECT_SOURCE_DIR}/${component}/*")
  foreach (item IN LISTS items)
    if (IS_DIRECTORY "${item}")
      glob(files FILES_ONLY "${item}/*")
      if (NOT files)
        continue()
      endif()
    else()
      list(APPEND files "${item}")
    endif()
    get_filename_component(name "${item}" NAME_WE)
    string(REPLACE " " "-" name "${name}")
    set(target ${PROJECT_NAME}-${component}-${name})
    set(alias ${PROJECT_NAME}::${component}::${name})
    add_executable(${target} ${files})
    add_executable(${alias} ALIAS ${target})
    add_test(${alias} ${target})
    target_link_libraries(${target}
      PRIVATE
        $<TARGET_NAME_IF_EXISTS:${PROJECT_NAME}::${PROJECT_NAME}>)
    set_property(TARGET ${target} PROPERTY
      RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${component})
  endforeach()
endfunction()
