include_guard(GLOBAL)

function (ixm_coven_options_create)
  set(options BENCHMARKS;EXAMPLES;TESTS;DOCS)
  foreach (opt IN LISTS options)
    if (${PROJECT_NAME}_STANDALONE)
      option(BUILD_${opt} "Build ${lower}" ON)
    endif()
    string(TOLOWER ${opt} lower)
    set(name ${PROJECT_NAME}_BUILD_${opt})
    set(docs "Build ${lower} for '${PROJECT_NAME}'")
    set(initial OFF)
    if (BUILD_${opt} OR ${PROJECT_NAME}_STANDALONE)
      set(initial ON)
    endif()
    option(${name} "${docs}" ${initial})
  endforeach()
endfunction()
