include_guard(GLOBAL)

function (ixm_coven_program_create)
  ixm_coven_create_project_program()
  ixm_coven_create_bin_program()
endfunction()

function (ixm_coven_create_project_program)
  if (NOT IS_DIRECTORY "${PROJECT_SOURCE_DIR}/src")
    return()
  endif()
  glob(files "${PROJECT_SOURCE_DIR}/src/main.*")
  if (NOT files)
    return()
  endif()

  add_executable(main)
  set_property(TARGET main PROPERTY OUTPUT_NAME ${PROJECT_NAME})
  target_sources(main PRIVATE ${files})
  add_executable(${PROJECT_NAME}::main ALIAS main)
  target_link_libraries(main
    PRIVATE
      $<TARGET_NAME_IF_EXISTS:${PROJECT_NAME}::${PROJECT_NAME}>)
endfunction()

function (ixm_coven_create_bin_program)
  if (NOT IS_DIRECTORY "${PROJECT_SOURCE_DIR}/src/bin")
    return()
  endif()
  glob(files FILES_ONLY "${PROJECT_SOURCE_DIR}/src/bin/*")
  if (NOT files)
    return()
  endif()
  foreach (file IN LISTS files)
    get_filename_component(name "${file}" NAME_WE)
    set(target ${PROJECT_NAME}-${name})
    add_executable(${target})
    add_executable(${PROJECT_NAME}::${name} ALIAS ${target})
    set_property(TARGET ${target} PROPERTY OUTPUT_NAME ${name})
    target_sources(${target} PRIVATE "${file}")
    target_link_libraries(${target}
      PRIVATE
        $<TARGET_NAME_IF_EXISTS:${PROJECT_NAME}::${PROJECT_NAME}>)
  endforeach()
endfunction()

#function (ixm_layout_add_srcbin)
#  foreach (ext IN LISTS IXM_SOURCE_EXTENSIONS)
#    file(GLOB files
#      LIST_DIRECTORIES OFF
#      CONFIGURE_DEPENDS
#      "${PROJECT_SOURCE_DIR}/src/bin/*.${ext}")
#    list(APPEND sources ${files})
#  endforeach()
#  foreach (source IN LISTS sources)
#    ixm_layout_support_create(${source})
#    add_executable(${PROJECT_NAME}::${name} ALIAS ${target})
#    set_target_properties(${target} PROPERTIES OUTPUT_NAME ${name})
#  endforeach()
#endfunction()
#
#function (ixm_layout_add_srcdirs)
#  file(GLOB entries LIST_DIRECTORIES OFF "${PROJECT_SOURCE_DIR}/src/*")
#  list(REMOVE_ITEM entries "${PROJECT_SOURCE_DIR}/src/bin")
#  foreach (entry IN LISTS entries)
#    if (NOT IS_DIRECTORY ${entry})
#      continue()
#    endif()
#    ixm_layout_support_create(${entry})
#    add_executable(${PROJECT_NAME}::${name} ALIAS ${target})
#    set_target_properties(${target} PROPERTIES OUTPUT_NAME ${name})
#    foreach (ext IN LISTS IXM_SOURCE_EXTENSIONS)
#      target_glob_sources(${target} PRIVATE "${entry}/*.${ext}")
#    endforeach()
#  endforeach()
#endfunction()
