include_guard(GLOBAL)

function (ixm_coven_program_create)
  ixm_coven_program_dir()
endfunction()

function (ixm_coven_create_project_program)
  ixm_coven_program_check("src")
  ixm_coven_program_glob(files "src/main.*")
  set_property(TARGET ${PROJECT_NAME}-main PROPERTY OUTPUT_NAME ${PROJECT_NAME})
endfunction()

function (ixm_coven_create_bin_program)
  ixm_coven_program_check("src/bin")
  ixm_coven_program_glob(files "src/bin/*")
  foreach (file IN LISTS files)
    get_filename_component(name "${file}" NAME_WE)
  endforeach()
endfunction()

function (ixm_coven_program_dir)
  glob(mains FILES_ONLY "${PROJECT_SOURCE_DIR}/src/*/main.*")
  if (NOT mains)
    return()
  endif()
  foreach (main IN LISTS mains)
    file(RELATIVE_PATH main ${PROJECT_SOURCE_DIR} ${main})
    get_filename_component(directory ${main} DIRECTORY)
    get_filename_component(name ${directory} NAME)
    ixm_coven_program_glob(files "${directory}/*")
    ixm_coven_program_add(${name} ${files})
  endforeach()
endfunction()

macro (ixm_coven_program_glob out-var expr)
  glob(${out-var} FILES_ONLY "${PROJECT_SOURCE_DIR}/${expr}")
  if (NOT ${out-var})
    return()
  endif()
endmacro()

macro (ixm_coven_program_check directory)
  if (NOT IS_DIRECTORY "${PROJECT_SOURCE_DIR}/${directory}")
    return()
  endif()
endmacro()
