include_guard(GLOBAL)

function (ixm_coven_tests_create)
  glob(items "${PROJECT_SOURCE_DIR}/tests/*")
  foreach (item IN LISTS items)
    get_filename_component(name ${item} NAME_WE)
    set(target ${PROJECT_NAME}-test-${name})
    set(alias ${PROJECT_NAME}::test::${name})
    if (IS_DIRECTORY ${item})
      glob(files FILES_ONLY "${item}/*")
      if (NOT files)
        continue()
      endif()
    else()
      list(APPEND files ${item})
    endif()
    add_executable(${target} ${files})
    add_executable(${alias} ALIAS ${target})
    add_test(test-${PROJECT_NAME}-${name} ${target})
  endforeach()
endfunction()

# No-op so we can have full control over projects while generating a custom
# test target
#function (enable_testing)
#endfunction()
