include_guard(GLOBAL)

function (ixm_project_common_version name)
  if (DEFINED PROJECT_VERSION)
    return()
  endif()
  set(VERSION 0.1.0)
  set(MAJOR 0)
  set(MINOR 1)
  set(PATCH 0)
  set(TWEAK)
  set(${name}_VERSION ${VERSION} PARENT_SCOPE)
  set(PROJECT_VERSION ${VERSION} PARENT_SCOPE)
  foreach (var IN ITEMS MAJOR MINOR PATCH TWEAK)
    set(${name}_VERSION_${var} ${${var}} PARENT_SCOPE)
    set(PROJECT_VERSION_${var} ${${var}} PARENT_SCOPE)
  endforeach()
endfunction()

function (ixm_project_common_standalone name)
  set(PROJECT_STANDALONE OFF)
  if (CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    set(PROJECT_STANDALONE ON)
  endif()
  cache(BOOL ${name}_STANDALONE ${PROJECT_STANDALONE})
  global(${name}_STANDALONE ${PROJECT_STANDALONE})
  upvar(PROJECT_STANDALONE)
endfunction()
