include_guard(GLOBAL)

function (ixm_project_layout_discovery layout)
  ixm_project_layout_search_paths(${layout})
  foreach (path IN LISTS paths)
    if (EXISTS "${path}")
      set_property(GLOBAL PROPERTY IXM_CURRENT_LAYOUT_NAME ${layout})
      set_property(GLOBAL PROPERTY IXM_CURRENT_LAYOUT_FILE ${path})
      return()
    endif()
  endforeach()
  fatal("Could not discover layout '${layout}'")
endfunction()

function (ixm_project_layout_search_paths layout)
  foreach (dir IN LISTS IXM_LAYOUT_PATH CMAKE_MODULE_PATH IXM_ROOT)
    list(APPEND paths "${dir}/layouts/${layout}.cmake")
    list(APPEND paths "${dir}/${layout}/layout.cmake")
    list(APPEND paths "${dir}/${layout}.cmake")
  endforeach()
endfunction()
