include_guard(GLOBAL)

#event(ADD <action...> TO <event>...)
#event(RM <action...> FROM <event>...)
#event(EMIT <event> <values...>)

function (ixm_event_add)
  void(TO REMAINDER)
  parse(${ARGN} @ARGS=+ TO)
  if (NOT REMAINDER)
    log(FATAL "event(ADD) requires at least one command to be added")
  endif()
  foreach (event IN LISTS TO)
    get_property(handlers GLOBAL PROPERTY ixm::event::${event})
    list(APPEND handlers ${REMAINDER})
    list(REMOVE_DUPLICATES handlers)
    set_property(GLOBAL PROPERTY ixm::event::${event} ${handlers})
    variable_watch(ixm::event::${event} ixm::event::handler)
  endforeach()
endfunction()