include_guard(GLOBAL)

function (ixm::event::handler variable access value current stack)
  if (access STREQUAL "MODIFIED_ACCESS")
    get_property(handlers GLOBAL PROPERTY ${variable})
    foreach (handler IN LISTS handlers)
      if (NOT COMMAND ${handler})
        log(WARNING "Skipping event handler '${handler}' for event '${variable}'. Not a COMMAND")
        continue()
      endif()
      invoke(${handler} ${value})
    endforeach()
  endif()
endfunction()