include_guard(GLOBAL)

function (ixm::event::handler variable access value current stack)
  if (access STREQUAL "MODIFIED_ACCESS")
    get_property(handlers GLOBAL PROPERTY ${variable})
    foreach (handler IN LISTS handlers)
      if (NOT COMMAND ${handler})
        log(WARNING "Skipping event handler '${handler}' for event '${variable}'. Not a COMMAND")
        continue()
      endif()
      invoke(${handler} ${value})
    endforeach()
  endif()
endfunction()

function (cmake::package variable access value current stack)
  if (NOT variable STREQUAL "CMAKE_FIND_PACKAGE_NAME")
    log(FATAL "cmake::package may only be used on CMAKE_FIND_PACKAGE_NAME")
  endif()
  if (access STREQUAL "MODIFIED_ACCESS")
    ixm_find_package_constructor(${value})
    get_property(events GLOBAL PROPERTY ixm::events::find-package::begin)
  elseif (access STREQUAL "REMOVED_ACCESS")
    ixm_find_package_destructor()
    get_property(name GLOBAL PROPERTY ixm::find)
    string(TOUPPER ${name} upper)
    set(${name}_FOUND ${${name}_FOUND} PARENT_SCOPE)
  endif()
endfunction()

function (cmake::directory variable access value current stack)
  if (NOT variable STREQUAL "CMAKE_CURRENT_LIST_DIR")
    log(FATAL "cmake::directory may only be used on CMAKE_CURRENT_LIST_DIR")
  endif()
  if (access STREQUAL "MODIFIED_ACCESS" AND value)
    get_property(events GLOBAL PROPERTY ixm::events::configure::begin)
    foreach (event IN LISTS events)
      invoke(${event} ${value})
    endforeach()
  elseif (access STREQUAL "MODIFIED_ACCESS" AND value STREQUAL "")
    get_property(events GLOBAL PROPERTY ixm::events::configure::end)
    foreach (event IN LISTS events)
      invoke(${event})
    endforeach()
  endif()
endfunction()
