include_guard(GLOBAL)

function (ixm_event_remove)
  void(TO REMAINDER)
  parse(${ARGN} @ARGS=+ FROM)
  if (NOT REMAINDER)
    log(FATAL "event(REMOVE) requires at least one command to be removed")
  endif()
  foreach (event IN LISTS FROM)
    get_property(handlers GLOBAL PROPERTY ixm::event::${event})
    list(REMOVE_ITEM handlers ${REMAINDER})
    list(REMOVE_DUPLICATES handlers)
    set_property(GLOBAL PROPERTY ixm::event::${event} ${handlers})
  endforeach()
endfunction()