include_guard(GLOBAL)

macro(debug)
  foreach(var ${ARGN})
    if (DEFINED ${var})
      message("${var} := ${${var}}")
    else()
      message("${var} := $<UNDEFINED>")
    endif()
  endforeach()
endmacro()
