include_guard(GLOBAL)

macro(ixm_var var lookup default)
  set(__@default ${default} ${ARGN})
  if (DEFINED ${lookup})
    set(__@default ${${lookup}} ${ARGN})
  endif()
  set(${var} ${__\@default})
  unset(__@default)
endmacro()
