include_guard(GLOBAL)

function (ixm_attribute_get out-var)
  unset(DOMAIN)
  unset(NAME)
  unset(TARGET)
  unset(PROPERTY)
  parse(${ARGN} @ARGS=? DOMAIN NAME TARGET PROPERTY)
  if (DEFINED TARGET AND DEFINED NAME)
    log(FATAL "attribute(GET) can only take NAME or TARGET")
  endif()
  if (NAME)
    assign(domain ? DOMAIN PROJECT_NAME : "IXM")
    string(TOLOWER "${domain}" domain) 
    string(TOLOWER "${NAME}" name)
    get_property(value GLOBAL PROPERTY "attr:${domain}:${name}")
    set(${out-var} ${value} PARENT_SCOPE)
  endif()
endfunction()