include_guard(GLOBAL)

function (ixm_attribute_target target)
  parse(${ARGN} @ARGS=1 PROPERTY)
  if (NOT TARGET ${target})
    log(FATAL "'${target}' does not name an existing target")
  endif()
  get_property(aliased TARGET ${target} PROPERTY ALIASED_TARGET)
  assign(target ? aliased : ${target})
  set(ARGN ${REMAINDER})
  list(LENGTH ARGN length)
  if (length GREATER 1)
    list(GET ARGN 0 action)
    set(valid CONCAT APPEND ASSIGN)
    if (NOT action IN_LIST valid)
      unset(action)
    else()
      list(REMOVE_AT ARGN 0)
      if (action STREQUAL "CONCAT")
        set(action "APPEND_STRING")
      elseif (action STREQUAL "ASSIGN")
        unset(action)
      endif()
    endif()
  endif()
  set_property(TARGET ${target} PROPERTY ${action} ${PROPERTY} ${ARGN})
endfunction()