include_guard(GLOBAL)

function(aspect @aspect:action @aspect:name)
  if (@aspect:action STREQUAL "SET")
  parse(${ARGN} @ARGS=+ WITH)
  string(TOLOWER "${\@aspect\:name}" @aspect:name)
  inspect(CMAKE_CURRENT_SOURCE_DIR)
  set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY ${\@aspect\:name} ${WITH})
  elseif (@aspect:action STREQUAL "GET")
    parse(${ARGN} @ARGS=? AS)
    assign(@aspect:as ? AS : "${\@aspect\:name}")
    string(TOLOWER "${\@aspect\:name}" @aspect:name)
    get_property(@aspect:current DIRECTORY PROPERTY ${\@aspect\:name})
    if (DEFINED PROJECT_SOURCE_DIR)
      get_property(@aspect:project DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY ${\@aspect\:name})
    endif()
    get_property(@aspect:ixm DIRECTORY "${ixm_SOURCE_DIR}" PROPERTY ${\@aspect\:name})
    inspect(@aspect:current @aspect:project @aspect:ixm)
    assign(@aspect:value ? @aspect:current @aspect:project @aspect:ixm)
    if (NOT DEFINED @aspect:value)
      return()
    endif()
    set(${\@aspect\:as} ${\@aspect\:value} PARENT_SCOPE)
  endif()
endfunction()
