include_guard(GLOBAL)

function(aspect action name)
  void(WITH AS)
  if (action STREQUAL "SET")
    parse(${ARGN} @ARGS=+ WITH)
    string(TOLOWER "${name}" name)
    set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY 🈯::${name} ${WITH})
  elseif (action STREQUAL "GET")
    parse(${ARGN} @ARGS=? AS)
    assign(as ? AS : "${name}")
    string(TOLOWER "${name}" name)
    get_property(current DIRECTORY PROPERTY 🈯::${name})
    get_property(root DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY 🈯::${name})
    if (DEFINED PROJECT_SOURCE_DIR)
      get_property(project DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY 🈯::${name})
    endif()
    get_property(ixm DIRECTORY "${ixm_SOURCE_DIR}" PROPERTY 🈯::${name})
    assign(value ? root project current ixm)
    if (NOT DEFINED value)
      return()
    endif()
    set(${as} ${value} PARENT_SCOPE)
  endif()
endfunction()
