include_guard(GLOBAL)

# TODO: Figure out why we can't use dict:<action> attribute
#       for dynamic call lookups
function (dict action name)
  if (action STREQUAL "LOAD")
    ixm_dict_load(${name} ${ARGN})
  elseif (action STREQUAL "SAVE")
    ixm_dict_save(${name} ${ARGN})
  elseif (action STREQUAL "JSON")
    ixm_dict_json(${name} ${ARGN})
  elseif (action STREQUAL "TRANSFORM")
    error("dict(TRANSFORM) is not yet implemented")
  elseif (action STREQUAL "INSERT")
    ixm_dict_insert(${name} ${ARGN})
  elseif (action STREQUAL "SET")
    ixm_dict_set(${name} ${ARGN})
  elseif (action STREQUAL "REMOVE")
    ixm_dict_remove(${name} ${ARGN})
  elseif (action STREQUAL "CLEAR")
    ixm_dict_clear(${name} ${ARGN})
  elseif (action STREQUAL "MERGE")
    ixm_dict_merge(${name} ${ARGN})
  elseif (action STREQUAL "KEYS")
    ixm_dict_keys(${name} ${ARGN})
  elseif (action STREQUAL "GET")
    ixm_dict_get(${name} ${ARGN})
  else()
    log(FATAL "dict(${action}) is an invalid operation")
  endif()
  set(returns KEYS GET)
  if (action IN_LIST returns)
    list(GET ARGN -1 @dict:returns)
    set(${\@dict\:returns} ${${\@dict\:returns}} PARENT_SCOPE)
  endif()
endfunction()