include_guard(GLOBAL)
import(IXM::Event::*)

function (event action name)
  if (action STREQUAL "ADD")
  elseif (action STREQUAL "REMOVE" OR action STREQUAL "RM")
  else()
    log(FATAL "event(${action}) is an invalid operation")
  endif()
endfunction()
