include_guard(GLOBAL)

import(IXM::Event::*)

function (event subcommand)
  if (subcommand STREQUAL "ADD")
    ixm_event_add(${ARGN})
  elseif (subcommand STREQUAL "EMIT")
    ixm_event_emit(${ARGN})
  elseif (subcommand STREQUAL "REMOVE")
    ixm_event_remove(${ARGN})
  else()
    log(FATAL "event(${subcommand}) is not a valid subcommand")
  endif()
endfunction()
