include_guard(GLOBAL)

import(IXM::Find::*)

function(Find action)
  get_property(valid-actions GLOBAL PROPERTY IXM_FIND_ACTIONS)
  if (NOT action IN_LIST valid-actions)
    error("'Find(${action})' is not a valid operation")
  endif()
  get_property(command GLOBAL PROPERTY IXM_FIND_${action})
  if (NOT command)
    error("'Find(${action})' command implementation is missing")
  endif()
  if (NOT COMMAND ${command})
    error("'Find(${action})' resolves to invalid command '${command}'")
  endif()
  invoke(${command} ${ARGN})
endfunction()
