include_guard(GLOBAL)

import(IXM::Generate::*)

function (generate subcommand)
  set(precompiled-header "PCH" "PRECOMPILED_HEADER")
  set(response-file "RSP" "RESPONSE_FILE")
  set(unity-build "UNITY" "UNITY_BUILD")
  set(protobuf "PROTO" "PROTOBUF")
  set(bison "BISON" "YACC")
  set(flex "FLEX" "LEX")

  if (subcommand IN_LIST precompiled-header)
    ixm_generate_precompiled_header(${ARGN})
  elseif (subcommand IN_LIST response-file)
    ixm_generate_response_file(${ARGN})
  elseif (subcommand IN_LIST unity-build)
    ixm_generate_unity_build(${ARGN})
  elseif (subcommand IN_LIST protobuf)
    ixm_generate_protobuf(${ARGN})
  elseif (subcommand IN_LIST bison)
    ixm_generate_bison(${ARGN})
  elseif (subcommand IN_LIST flex)
    ixm_generate_flex(${ARGN})
  else()
    log(FATAL "generate(${subcommand}) is not a valid subcommand")
  endif()
endfunction()
