include_guard(GLOBAL)

import(IXM::Target::*)

# Common arguments:
# ALIAS <name>
# COMPONENT <name>
# ALL (flag)
function (target subcommand)
  if (subcommand STREQUAL "APP")
    ixm_target_app(${ARGN})
  elseif (subcommand STREQUAL "ARCHIVE")
    ixm_target_archive(${ARGN})
  elseif (subcommand STREQUAL "COMMAND")
    ixm_target_command(${ARGN})
  elseif (subcommand STREQUAL "COMPILE")
    ixm_target_compile(${ARGN})
  elseif (subcommand STREQUAL "FRAMEWORK")
    ixm_target_framework(${ARGN})
  elseif (subcommand STREQUAL "IMPORT")
    ixm_target_import(${ARGN})
  elseif (subcommand STREQUAL "INTERFACE")
    ixm_target_interface(${ARGN})
  elseif (subcommand STREQUAL "LIBRARY")
    ixm_target_library(${ARGN})
  elseif (subcommand STREQUAL "PHONY")
    ixm_target_phony(${ARGN})
  elseif (subcommand STREQUAL "PLUGIN")
    ixm_target_plugin(${ARGN})
  elseif (subcommand STREQUAL "PROGRAM")
    ixm_target_program(${ARGN})
  elseif (subcommand STREQUAL "SERVICE")
    ixm_target_service(${ARGN})
  elseif (subcommand STREQUAL "SOURCES")
    ixm_target_sources(${ARGN})
  elseif (subcommand STREQUAL "TEST")
    ixm_target_test(${ARGN})
  elseif (subcommand STREQUAL "TOOL")
    ixm_target_tool(${ARGN})
    log(FATAL "target(${subcommand}) is not a valid subcommand")
  endif()
endfunction ()

# Like target_link_libraries, but copies all custom IXM properties
# TODO: What is the "subcommand" we're going to name this?
function(target_copy_properties target)
  get_property(interface-properties GLOBAL PROPERTY IXM_INTERFACE_PROPERTIES)
  get_property(private-properties GLOBAL PROPERTY IXM_PRIVATE_PROPERTIES)

  parse(${ARGN} @ARGS=* PRIVATE PUBLIC INTERFACE)

  # TODO: make target verification occur *outside* of copy loops
  foreach (tgt IN LISTS PRIVATE PUBLIC)
    if (NOT TARGET ${tgt})
      log(FATAL "'${tgt}' is not a known target")
    endif()
    foreach (property IN LISTS private-properties)
      get_target_property(value ${tgt} ${property})
      if (NOT value)
        continue()
      endif()
      set_property(TARGET ${target} APPEND PROPERTY ${property} ${value})
    endforeach()
  endforeach()
endfunction()
