find(LIBRARY SDL2_image COMPONENT Image)
find(LIBRARY SDL2_mixer COMPONENT Mixer)
find(LIBRARY SDL2_ttf COMPONENT Font)
find(LIBRARY SDL2main COMPONENT Main)
find(LIBRARY SDL2_net COMPONENT Net)
find(LIBRARY SDL2)
find(INCLUDE SDL2/SDL.h)

if (SDL2_INCLUDE_DIR)
  file(STRINGS ${SDL2_INCLUDE_DIR}/SDL2/SDL_version.h version-file
    REGEX "#define SDL_(MAJOR|MINOR|PATCHLEVEL).*")
endif()

target_link_libraries(SDL2::SDL2 INTERFACE
  $<TARGET_NAME_IF_EXISTS:SDL2::Image>
  $<TARGET_NAME_IF_EXISTS:SDL2::Mixer>
  $<TARGET_NAME_IF_EXISTS:SDL2::Font>
  $<TARGET_NAME_IF_EXISTS:SDL2::Net>)
