include_guard(GLOBAL)

include(CMakePushCheckState)
include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)

function (check_compiler_flag flag variable)
  argparse(OPTIONS QUIET VALUES LANGUAGE ${ARGN})
  cmake_push_check_state()
  get(CMAKE_REQUIRED_QUIET ARG_QUIET OFF)

  if (ARG_LANGUAGE STREQUAL "CXX")
    check_cxx_compiler_flag(${flag} ${variable})
  elseif (ARG_LANGUAGE STREQUAL "C")
    check_c_compiler_flag(${flag} ${variable})
  else()
    error("LANGUAGE must be either: CXX C")
  endif()
  cmake_pop_check_state()
  parent_scope(${variable})
endfunction()
